name: Publish to npm
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn build
      - run: yarn publish --private
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}