name: Run tests on pull request to development branch
on: 
  pull_request:
    branches:
      - development
jobs: 
  run_tests:
    runs-on: ubuntu-latest
    env:
      CONNECTION_STRING: mongodb://127.0.0.1/agenda
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '12.x'
          cache: yarn
      - name: Setup MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with: 
          mongodb-version: '4.4'
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}          
      - name: Install dependencies 
        run: yarn
      - name: Run tests
        run: yarn --cwd ./api/ test --coverage
      - name: Report tests coverage
        uses: romeovs/lcov-reporter-action@v0.2.19
        with:
          lcov-file: ./api/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
